name = "PhyloGaussianBeliefProp"
uuid = "e3084505-90a0-4799-8167-4168d9f39f7c"
authors = ["Cecile Ane <cecileane@users.noreply.github.com>", "Benjamin Teo <bstkj@users.noreply.github.com>", "and contributors"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
