name = "PhyloGaussianBeliefProp"
uuid = "e3084505-90a0-4799-8167-4168d9f39f7c"
authors = ["Cecile Ane <cecileane@users.noreply.github.com>", "Benjamin Teo <bstkj@users.noreply.github.com>", "and contributors"]
version = "0.1.0"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
PhyloNetworks = "33ad39ac-ed31-50eb-9b15-43d0656eaa72"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
MetaGraphsNext = "0.6"
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
